services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/case_manager
      PHX_HOST: "localhost"
    ports:
      - "443:443"
    depends_on:
      - db
    command: >
      bash -c "bin/migrate && bin/server"

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: case_manager
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
