services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
      TOKEN_SIGNING_SECRET: /run/secrets/token_signing_secret
      PHX_HOST: "localhost"
      SSL_KEY_FILE: /run/secrets/ssl_key.pem
      SSL_CERT_FILE: /run/secrets/ssl_cert.pem
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "443:443"
      - "4000:4000"
    depends_on:
      - db
    command: >
      bash -c "bin/migrate && bin/server"
    secrets:
      - databaseurl
      - secretkeybase
      - ssl_key.pem
      - ssl_cert.pem

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespassword
      POSTGRES_DB: case_manager
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgrespassword

secrets:
  databaseurl:
    file: ./.secrets/.databaseurl
  secretkeybase:
    file: ./.secrets/.secretkeybase
  postgrespassword:
    file: ./.secrets/.postgrespassword
  token_signing_secret:
    file: ./.secrets/.token_signing_secret
  ssl_key.pem:
    file: ./.secrets/.ssl_key.pem
  ssl_cert.pem:
    file: ./.secrets/.ssl_cert.pem

volumes:
  db_data:
