defmodule CaseManager.Repo.Migrations.RemoveManyToManyForContactInfos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:phone) do
      add :team_id,
          references(:team,
            column: :id,
            name: "phone_to_team_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    alter table(:ip) do
      add :team_id,
          references(:team,
            column: :id,
            name: "ip_to_team_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    alter table(:email) do
      add :team_id,
          references(:team,
            column: :id,
            name: "email_to_team_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:email, "email_to_team_fkey")

    alter table(:email) do
      remove :team_id
    end

    drop constraint(:ip, "ip_to_team_fkey")

    alter table(:ip) do
      remove :team_id
    end

    drop constraint(:phone, "phone_to_team_fkey")

    alter table(:phone) do
      remove :team_id
    end
  end
end
