defmodule CaseManager.Repo.Migrations.AddContraintsToAlerts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:alerts) do
      remove :temp
      modify :link, :text, null: false
      modify :risk_level, :text, null: false
      modify :title, :text, null: false
      modify :alert_id, :text, null: false
    end
  end

  def down do
    alter table(:alerts) do
      modify :alert_id, :text, null: true
      modify :title, :text, null: true
      modify :risk_level, :text, null: true
      modify :link, :text, null: true
      add :temp, :text
    end
  end
end
