defmodule CaseManager.Repo.Migrations.DropForceUserAttrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      modify :role, :text, null: true
      modify :team_id, :uuid, null: true
      modify :last_name, :text, null: true
      modify :first_name, :text, null: true
    end
  end

  def down do
    alter table(:user) do
      modify :first_name, :text, null: false
      modify :last_name, :text, null: false
      modify :team_id, :uuid, null: false
      modify :role, :text, null: false
    end
  end
end
