defmodule CaseManager.Repo.Migrations.CreateTeamRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_phone, primary_key: false) do
      add :team_id,
          references(:team,
            column: :id,
            name: "team_phone_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :phone_id,
          references(:phone,
            column: :id,
            name: "team_phone_phone_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create table(:team_ip, primary_key: false) do
      add :team_id,
          references(:team,
            column: :id,
            name: "team_ip_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :ip_id,
          references(:ip, column: :id, name: "team_ip_ip_id_fkey", type: :uuid, prefix: "public"),
          primary_key: true,
          null: false
    end

    create table(:team_email, primary_key: false) do
      add :team_id,
          references(:team,
            column: :id,
            name: "team_email_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :email_id,
          references(:email,
            column: :id,
            name: "team_email_email_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    alter table(:team) do
      remove :is_mssp
      remove :phone
      remove :email
      remove :ip
      add :ip_id, :uuid
      add :email_id, :uuid
      add :phone_id, :uuid
      add :type, :text
    end
  end

  def down do
    alter table(:team) do
      remove :type
      remove :phone_id
      remove :email_id
      remove :ip_id
      add :ip, :text
      add :email, :text
      add :phone, :text
      add :is_mssp, :boolean, default: false
    end

    drop constraint(:team_email, "team_email_team_id_fkey")

    drop constraint(:team_email, "team_email_email_id_fkey")

    drop table(:team_email)

    drop constraint(:team_ip, "team_ip_team_id_fkey")

    drop constraint(:team_ip, "team_ip_ip_id_fkey")

    drop table(:team_ip)

    drop constraint(:team_phone, "team_phone_team_id_fkey")

    drop constraint(:team_phone, "team_phone_phone_id_fkey")

    drop table(:team_phone)
  end
end
