defmodule CaseManager.Repo.Migrations.AddFkeyCheckForUserOnComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comment) do
      modify :user_id,
             references(:user,
               column: :id,
               name: "comment_to_user_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:comment, [:user_id])
  end

  def down do
    drop_if_exists index(:comment, [:user_id])

    drop constraint(:comment, "comment_to_user_fkey")

    alter table(:comment) do
      modify :user_id, :uuid
    end
  end
end
