defmodule CaseManager.Repo.Migrations.TeamsAddMissingDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team) do
      modify :type, :text, default: "Customer"
    end
  end

  def down do
    alter table(:team) do
      modify :type, :text, default: nil
    end
  end
end
