defmodule :"Elixir.CaseManager.Repo.Migrations.Add-file-table" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:file, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text
      add :content_type, :text
      add :binary_data, :binary
    end
  end

  def down do
    drop table(:file)
  end
end
