defmodule :"Elixir.CaseManager.Repo.Migrations.Add-realtionship" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:file) do
      add :case_id,
          references(:case,
            column: :id,
            name: "file_to_case_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:file, "file_to_case_fkey")

    alter table(:file) do
      remove :updated_at
      remove :inserted_at
      remove :case_id
    end
  end
end
