defmodule CaseManager.Repo.Migrations.AddNotNullToFile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      modify :team_id, :uuid, null: true
    end

    alter table(:file) do
      modify :case_id, :uuid, null: true
      modify :binary_data, :binary, null: false
      modify :content_type, :text, null: false
      modify :filename, :text, null: false
    end
  end

  def down do
    alter table(:file) do
      modify :filename, :text, null: true
      modify :content_type, :text, null: true
      modify :binary_data, :binary, null: true
      modify :case_id, :uuid, null: false
    end

    alter table(:user) do
      modify :team_id, :uuid, null: false
    end
  end
end
