defmodule CaseManager.Repo.Migrations.NilifyUserOnComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      modify :team_id, :uuid, null: false
      modify :role, :text, null: false
      modify :last_name, :text, null: false
      modify :first_name, :text, null: false
    end

    alter table(:ip) do
      modify :version, :text, null: false
    end

    drop constraint(:comment, "comment_to_user_fkey")

    alter table(:comment) do
      modify :user_id,
             references(:user,
               column: :id,
               name: "comment_to_user_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             ),
             null: true
    end
  end

  def down do
    drop constraint(:comment, "comment_to_user_fkey")

    alter table(:comment) do
      modify :user_id,
             references(:user,
               column: :id,
               name: "comment_to_user_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             ),
             null: false
    end

    alter table(:ip) do
      modify :version, :text, null: true
    end

    alter table(:user) do
      modify :first_name, :text, null: true
      modify :last_name, :text, null: true
      modify :role, :text, null: true
      modify :team_id, :uuid, null: true
    end
  end
end
