defmodule CaseManager.Repo.Migrations.AddRelationsshipAlertToTeams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:alerts), :team, to: :team_id

    alter table(:alerts) do
      modify :team_id, :uuid, null: false
    end
  end

  def down do
    alter table(:alerts) do
      modify :team, :uuid, null: true
    end

    rename table(:alerts), :team_id, to: :team
  end
end
