defmodule CaseManager.Repo.Migrations.ChangeToOnlyCreationTimestap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team) do
      remove :phone_id
      remove :email_id
      remove :ip_id
    end

    rename table(:alert), :start_time, to: :creation_time

    alter table(:alert) do
      remove :end_time
      modify :creation_time, :utc_datetime
    end
  end

  def down do
    alter table(:alert) do
      modify :start_time, :utc_datetime
      add :end_time, :utc_datetime, null: false
    end

    rename table(:alert), :creation_time, to: :start_time

    alter table(:team) do
      add :ip_id, :uuid
      add :email_id, :uuid
      add :phone_id, :uuid
    end
  end
end
