defmodule CaseManager.Repo.Migrations.CreateAlertsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alerts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :alert_id, :text
      add :team, :uuid
      add :title, :text
      add :description, :text
      add :risk_level, :text
      add :start_time, :utc_datetime
      add :end_time, :utc_datetime
      add :link, :text
      add :temp, :text
      add :additional_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:alerts)
  end
end
