defmodule CaseManager.Repo.Migrations.RenameTokensToToken do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:token, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    alter table(:email) do
      remove :user_id
    end
  end

  def down do
    alter table(:email) do
      add :user_id,
          references(:user,
            column: :id,
            name: "email_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop table(:token)
  end
end
