defmodule CaseManager.Repo.Migrations.DisallowNilTimes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:alerts) do
      modify :end_time, :utc_datetime, null: false
      modify :start_time, :utc_datetime, null: false
    end
  end

  def down do
    alter table(:alerts) do
      modify :start_time, :utc_datetime, null: true
      modify :end_time, :utc_datetime, null: true
    end
  end
end
