defmodule CaseManager.Repo.Migrations.RenameRiskToSeverity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:cases), :risk_level, to: :severity)

    rename(table(:alerts), :risk_level, to: :severity)
  end

  def down do
    rename(table(:alerts), :severity, to: :risk_level)

    rename(table(:cases), :severity, to: :risk_level)
  end
end
