defmodule CaseManager.Repo.Migrations.EnforceRelationToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      add :archived_at, :utc_datetime_usec
    end

    drop_if_exists unique_index(:user, [:email], name: "user_unique_email_index")

    create unique_index(:user, [:email], where: "((archived_at IS NULL))", name: "user_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:user, [:email], name: "user_unique_email_index")

    create unique_index(:user, [:email], name: "user_unique_email_index")

    alter table(:user) do
      remove :archived_at
    end
  end
end
