defmodule CaseManager.Repo.Migrations.CreateSettingsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false)
      add(:value, :text, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')"))
      add(:updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')"))
    end

    create unique_index(:settings, [:key], name: "settings_key_index")

    alter table(:case_views) do
      modify(:last_viewed_at, :utc_datetime_usec, default: nil)
    end
  end

  def down do
    alter table(:case_views) do
      modify(:last_viewed_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')"))
    end

    drop_if_exists(unique_index(:settings, [:key], name: "settings_key_index"))

    drop(table(:settings))
  end
end
