defmodule CaseManager.Repo.Migrations.DropAdditionalData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:alerts) do
      remove(:encrypted_additional_data)
    end
  end

  def down do
    alter table(:alerts) do
      add(:encrypted_additional_data, :binary)
    end
  end
end
