defmodule CaseManager.Repo.Migrations.AddUserRoles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:soc_users) do
      add(:user_role, :text)
    end

    alter table(:company_users) do
      add(:user_role, :text)
    end
  end

  def down do
    alter table(:company_users) do
      remove(:user_role)
    end

    alter table(:soc_users) do
      remove(:user_role)
    end
  end
end
