defmodule CaseManager.Repo.Migrations.AddNewStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add(:resolution_type, :text)
    end
  end

  def down do
    alter table(:cases) do
      remove(:resolution_type)
    end
  end
end
