defmodule CaseManager.Repo.Migrations.AddRelationtionCompanySoc do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:companies) do
      add(:soc_id, references(:socs, column: :id, name: "companies_soc_id_fkey", type: :uuid, prefix: "public"))
    end

    drop(constraint("soc_company_accesses", "soc_company_accesses_pkey"))

    alter table(:soc_company_accesses) do
      modify(:company_id, :uuid, primary_key: true)
      modify(:soc_id, :uuid, primary_key: true)
      remove(:id)
    end
  end

  def down do
    drop(constraint("soc_company_accesses", "soc_company_accesses_pkey"))

    alter table(:soc_company_accesses) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      modify(:soc_id, :uuid, primary_key: false)
      modify(:company_id, :uuid, primary_key: false)
    end

    drop(constraint(:companies, "companies_soc_id_fkey"))

    alter table(:companies) do
      remove(:soc_id)
    end
  end
end
