defmodule CaseManager.Repo.Migrations.DisablePkeyCompUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint("company_users", "company_users_pkey"))

    alter table(:company_users) do
      modify(:user_id, :uuid)
    end

    execute("ALTER TABLE \"company_users\" ADD PRIMARY KEY (company_id)")
  end

  def down do
    alter table(:company_users) do
      modify(:user_id, :uuid)
    end

    execute("ALTER TABLE \"company_users\" DROP constraint company_users_pkey")

    execute("ALTER TABLE \"company_users\" ADD PRIMARY KEY (user_id, company_id)")
  end
end
