defmodule CaseManager.Repo.Migrations.UpdateUserAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify(:last_name, :text, null: false)
      modify(:first_name, :text, null: false)
    end
  end

  def down do
    alter table(:users) do
      modify(:first_name, :text, null: true)
      modify(:last_name, :text, null: true)
    end
  end
end
