defmodule CaseManager.Repo.Migrations.UseRisklevelForCases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:cases), :priority, to: :risk_level)

    alter table(:alerts) do
      modify(:company_id, :uuid, null: false)
    end
  end

  def down do
    alter table(:alerts) do
      modify(:company_id, :uuid, null: true)
    end

    rename(table(:cases), :risk_level, to: :priority)
  end
end
