defmodule CaseManager.Repo.Migrations.ChangeOnDeleteForComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:comment, "comment_to_user_fkey")

    alter table(:comment) do
      modify :user_id,
             references(:user,
               column: :id,
               name: "comment_to_user_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             ),
             null: false
    end
  end

  def down do
    drop constraint(:comment, "comment_to_user_fkey")

    alter table(:comment) do
      modify :user_id,
             references(:user,
               column: :id,
               name: "comment_to_user_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             ),
             null: true
    end
  end
end
