defmodule :"Elixir.CaseManager.Repo.Migrations.Lib.CaseManager.AppConfig.Setting.ex" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:setting, [:key], name: "setting_key_index")
  end

  def down do
    drop_if_exists unique_index(:setting, [:key], name: "setting_key_index")
  end
end
