name: Documentation CI

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation:

    name: Update documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.2' # [Required] Define the Elixir version
          otp-version: '26.0'      # [Required] Define the Erlang/OTP version

      - name: Cache dependencies and build
        uses: actions/cache@v4
        with:
          id: "cache-deps"
          path: |
            deps
            _build
          key: doc-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: doc-${{ runner.os }}-mix-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get
      
      - name: Generate Documentation
        run: mix docs
      
      - name: Include docs folder
        run: |
          sed -i '/\/docs\//d' .gitignore
      
      - name: Commit changes to documentation branch
        env:
          ATTR_NAME: 'github-actions[bot]'
          ATTR_EMAIL: 'github-actions[bot]@users.noreply.github.com'
        run: |
          git config --global user.name $ATTR_NAME
          git config --global user.email $ATTR_EMAIL
          git add docs/*
          git commit -am "Automatic docs generation"
          git fetch origin docs
          git push origin main:docs --force-with-lease
