# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Static Code Analysis CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:

    name: Analyze code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        id: "cache-deps"
        path: |
          deps
          _build
        key: dev-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: dev-${{ runner.os }}-mix-
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: mix deps.get
    - name: Check for unused dependencies
      run: mix deps.unlock --check-unused
    - name: Check code formatting
      run: mix format --check-formatted
    - name: Check for missing generation of migrations
      run: mix ash.codegen --check
    - name: credo
      run: mix credo
    - name: sobelow
      run: mix sobelow --config
    - name: hex audit
      run: mix hex.audit
    - name: mix_audit
      run: mix deps.audit
